
services:
  - type: web
    name: megalodon-md 
    env: node
    plan: free
    repo: https://github.com/DybyTech/MEGALODON-MD.git
    branch: main
    buildCommand: npm install
    startCommand: node index.js
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: MODE
        value: public
      - key: PREFIX
        value: .
      - key: BOT_NAME
        value: FRIDO DEV TECH BOT
      - key: OWNER_NUMBER
        value: 50948336180
